wip

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -74,11 +74,26 @@ jobs:
           sed -i '/USER/s/myuser/awx/' mock_awx/settings/__init__.py
           sed -i '/PASSWORD/s/mypassword/awx/' mock_awx/settings/__init__.py
 
+      - name: Check pytest-cov installation
+        run: uv pip list | grep pytest-cov || echo "pytest-cov NOT installed!"
+
+
       - name: Run pytest
-        run: uv run pytest -s -v  --cov=. --cov-report=xml
+        run: uv run pytest -s -v  --cov=. --cov-report=xml --cov-report=term
+
+      - name: Check for coverage report
+        run: |
+          if [ -f ./coverage.xml ]; then
+            echo "coverage.xml exists."
+            cat coverage.xml | head -n 20  # Print first 20 lines for debugging
+          else
+            echo "coverage.xml is missing!"
+            exit 1  # Fail the build if coverage.xml is missing
+          fi
+
 
       - name: Send code coverage report to Sonar Cloud
-        uses: SonarSource/sonarqube-scan-action@v4
+        uses: SonarSource/sonarqube-scan-action@v5
         env:
           METRICS_UTILITY_BUCKET_ACCESS_KEY: "myuseraccesskey"
           METRICS_UTILITY_BUCKET_ENDPOINT: "http://localhost:9000"
